<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.core.NestedExceptionTests" tests="4" skipped="0" failures="0" errors="0" timestamp="2021-06-20T08:06:56" hostname="gankangdembp" time="0.006">
  <properties/>
  <testcase name="nestedRuntimeExceptionWithRootCause()" classname="org.springframework.core.NestedExceptionTests" time="0.003"/>
  <testcase name="nestedCheckedExceptionWithRootCause()" classname="org.springframework.core.NestedExceptionTests" time="0.001"/>
  <testcase name="nestedRuntimeExceptionWithNoRootCause()" classname="org.springframework.core.NestedExceptionTests" time="0.001"/>
  <testcase name="nestedCheckedExceptionWithNoRootCause()" classname="org.springframework.core.NestedExceptionTests" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
