<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" tests="7" skipped="2" failures="0" errors="0" timestamp="2020-05-29T13:59:45" hostname="bamboo-18" time="0.007">
  <properties/>
  <testcase name="noOpShouldNotTimeOut" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.006"/>
  <testcase name="alwaysFailsButShouldBeIgnored" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0">
    <skipped/>
  </testcase>
  <testcase name="alwaysSucceeds" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="verifyBeforeClassAnnotation" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="verifyBeforeAnnotation" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="expectingAnIndexOutOfBoundsException" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0"/>
  <testcase name="failedAssumptionShouldPrecludeImminentFailure" classname="org.springframework.test.context.junit4.StandardJUnit4FeaturesSpringRunnerTests" time="0.0">
    <skipped/>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
